### ISSUE TITLE
NPE crash with server

### ISSUE THREAD

**Issue by AK9Official** [branchpanic/stockpile#45] opened 2019-04-27 00:32 UTC
Fabric Loader: 0.4.4 build 138
Yarn: 1.14 build 3

How to reproduce: Start server, connect to it with client...

https://gyazo.com/1dc8cf103975cd9bdfb1a1ef7d4f761c

**Comment by branchpanic** [comment] 2019-04-27 02:52
Thanks for the report. I believe I've already identified the cause of this in passing-- it should be fixed rather shortly in the next patch.

**Comment by AK9Official** [comment] 2019-04-27 03:00
Next patch soonish? Just curious :)

**Comment by branchpanic** [comment] 2019-04-27 04:55
Absolutely- I'm building the new version as I type this!

**Comment by branchpanic** [comment] 2019-04-27 05:33
Hang on for a second, I may have jumped to conclusions. It looks like I can't actually reproduce this on my end (my apologies, I could have sworn I tested this, but it must have been related to a different issue). At least in a development environment, a client can successfully join a server with Stockpile 1.0.1.

What other mods are present in your environment? Does removing Stockpile prevent the error from occurring?

**Comment by AK9Official** [comment] 2019-04-27 06:04
Removing stockpile solves it

**Comment by AK9Official** [comment] 2019-04-27 06:45
Have you tried outside of dev?

**Comment by branchpanic** [comment] 2019-04-27 16:57
Just did. I was able to connect to a server with just Fabric API 0.2.7 build 127 and Stockpile 1.0.1. Perhaps the issue is coming from a conflict rather than a bug in Stockpile on its own. 
![image](https://user-images.githubusercontent.com/3802908/56852569-e2e7f880-68ea-11e9-9fdc-d2cf3294bee7.png)

Here's a test build of 1.0.2 if you want to see if the problem persists with it as well. Version 1.0.2 does not bundle the Kotlin language adapter so you will need to download it manually if you haven't already.
[stockpile-1.0.2-server-npe-test+1.14.zip](https://github.com/branchpanic/stockpile/files/3124116/stockpile-1.0.2-server-npe-test%2B1.14.zip)

**Comment by AK9Official** [comment] 2019-04-27 20:06
As i did some more testing it seems like it was Composable Automation causing the crash on login. Sorry for bothering you!

**Comment by branchpanic** [comment] 2019-04-27 20:23
Ah, that's totally fine. No worries-- thanks for taking the time to contribute regardless!

**Closed by branchpanic** 2019-04-27 20:23 UTC
Labels: bug, can't reproduce, next patch
