### ISSUE TITLE
Unable to pickup a barrel once it's placed

### ISSUE THREAD

**Issue by poboy975** [branchpanic/stockpile#52] opened 2019-05-07 14:18 UTC
This seems similar to https://github.com/branchpanic/stockpile/issues/2
But I don't have any trash cans at all. I've got two barrels on the ground that wont let me pick them up, same break animation and instantly replace

**Comment by branchpanic** [comment] 2019-05-08 03:26
Was able to reproduce by breaking a Barrel from the front side. Simple fix, should be able to achieve this in the next patch!

**Comment by poboy975** [comment] 2019-05-08 23:33
As a work around, if I break the barrel from the side I can pick it up now?

**Comment by branchpanic** [comment] 2019-05-22 03:03
(looks like I forgot to close this one, oops)

**Closed** 2019-05-22 03:03 UTC
Labels: bug, next patch
