### ISSUE TITLE
[bug] extraction problems in smp

### ISSUE THREAD

**Issue by Yoghurt4C** [branchpanic/stockpile#46] opened 2019-04-28 15:53 UTC
sometimes the player stops being able to extract items from barrels on a dedicated server until they disconnect and log back in (which takes quite a while on 1.14)
`stockpile-1.0.1+1.14-Pre5`

**Comment by branchpanic** [comment] 2019-05-02 02:36
Ok, so I wasn't actually able to reproduce this even by running an auto-clicker for a while on a local server, but I *did* eliminate some sketchy code that seems like it could have contributed to the issue. This "fix" will be included in the next patch.

If you have any additional info you think might help (a mod list might be useful to see if it's a conflict), feel free to share it. I'll leave this with a "can't reproduce" label for now, but feel free to comment if the issue no longer persists in 1.0.3 once it's out in a day or two.

**Comment by apotheoseGrifter** [comment] 2019-05-03 19:25
I had this same issue on LAN. I initially thought it was a permission issue, since I was able to extract from the barrel and the host wasn't, but after find this issue we tried restarting the game. After that both of us were able to extract from it initially, but I came back to the barrel later during that same session and found I could no longer extract from it. Locking and unlocking the barrel worked normally at all times, if that's relevant.

Here's my modlist for conflict checking:
https://hastebin.com/jaducajedu.css

**Comment by branchpanic** [comment] 2019-05-03 20:54
Thanks for the info-- the bit about still being able to lock barrels helps. I'm going to release 1.0.3 shortly which may or may not fix this, so I'll keep the issue open. I still haven't been able to reproduce it even in a modpack with all of those mods, but I'll keep looking into it with 1.0.2 in the meantime.

**Comment by apotheoseGrifter** [comment] 2019-05-04 08:16
Updated today. After playing for several hours in which we had zero issues, it seems safe to say the problem is completely gone. :)

**Comment by branchpanic** [comment] 2019-05-04 18:11
Great, thanks for the confirmation! In that case I'll close off this issue now.

**Closed by branchpanic** 2019-05-04 18:11 UTC
Labels: bug, can't reproduce
